import getConfig from './getConfig';
import getSaveType from './getSaveType';
import packageManager from './pnpmPkgJson';
export { getConfig, getSaveType, packageManager };
export * from './createLatestManifestGetter';
export * from './getPinnedVersion';
export * from './packageIsInstallable';
export * from './readImporterManifest';
export * from './style';
export * from './updateToLatestSpecsFromManifest';
export declare const docsUrl: (cmd: string) => string;
